### ISSUE TITLE
5. Game Logic

### ISSUE THREAD

**Issue by dacasanovat** [MakeSchool-Tutorials/sa-2018-concentration#8]
In the following picture,

<img width="1186" alt="captura de pantalla 2018-07-04 a la s 2 45 34 p m" src="https://user-images.githubusercontent.com/31299884/42294816-f8d2526c-7f98-11e8-84fe-a586e69eb64a.png">

the last part is out of format.

**Comment by dionlarson** [comment]
Fixed
